<a href="https://colab.research.google.com/github/GomesGA/scikit_learn_models/blob/main/Projeto_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn import tree

#[height,weight,shoe size]
X = [[181,80,44],[177,70,43],[160,60,38],[154,54,37],[166,65,40],[190,90,47],[175,64,39],[177,70,40],[159,55,37],[171,75,42],[181,85,43]]
Y = [ "male", "female", "female", "female","male", "male", "male", "female", "male", "female","male"]

clf = tree.DecisionTreeClassifier()
clf = clf.fit(X,Y)
print(clf.predict([[190,70,43]]))
print(clf.predict([[156,72,48]]))

['male']
['female']


Challenge

1. Use any 3 Scikit-Learn Models on this dataset
2. Compare results
3. Print the best one

In [ ]:
import numpy as np

X = [[181,80,44],[177,70,43],[160,60,38],[154,54,37],[166,65,40],[190,90,47],[175,64,39],[177,70,40],[159,55,37],[171,75,42],[181,85,43]]
Y = [ "male", "female", "female", "female","male", "male", "male", "female", "male", "female","male"]

# Converter para arrays numpy para facilitar a manipulação
X_np = np.array(X)
Y_np = np.array(Y)

# Criar dados sintéticos adicionais
num_additional_samples = 90

# Estimativa de médias e desvios padrão dos dados originais para cada classe (male/female)
# Índices para 'male' e 'female' nos dados originais
male_indices = [i for i, label in enumerate(Y) if label == "male"]
female_indices = [i for i, label in enumerate(Y) if label == "female"]

X_male = X_np[male_indices]
X_female = X_np[female_indices]

# Calcular média e desvio padrão para cada feature em cada classe
mean_male = np.mean(X_male, axis=0)
std_male = np.std(X_male, axis=0)

mean_female = np.mean(X_female, axis=0)
std_female = np.std(X_female, axis=0)

# Gerar dados sintéticos baseados nas estatísticas estimadas
# Vamos gerar metade 'male' e metade 'female'
num_male_samples = num_additional_samples // 2
num_female_samples = num_additional_samples - num_male_samples

synthetic_X_male = np.random.normal(mean_male, std_male, size=(num_male_samples, X_np.shape[1]))
synthetic_Y_male = np.array(["male"] * num_male_samples)

synthetic_X_female = np.random.normal(mean_female, std_female, size=(num_female_samples, X_np.shape[1]))
synthetic_Y_female = np.array(["female"] * num_female_samples)

# Combinar os dados originais e sintéticos
X_larger = np.vstack((X_np, synthetic_X_male, synthetic_X_female))
Y_larger = np.concatenate((Y_np, synthetic_Y_male, synthetic_Y_female))

shuffle_indices = np.random.permutation(len(X_larger))
X_larger = X_larger[shuffle_indices]
Y_larger = Y_larger[shuffle_indices]

print(f"Tamanho da base de dados original: {len(X)}")
print(f"Tamanho da nova base de dados sintética: {len(X_larger)}")
print("\nPrimeiras 5 amostras da nova base de dados (X_larger):")
print(X_larger[:5])
print("\nPrimeiras 5 labels da nova base de dados (Y_larger):")
print(Y_larger[:5])

Tamanho da base de dados original: 11
Tamanho da nova base de dados sintética: 101

Primeiras 5 amostras da nova base de dados (X_larger):
[[183.02374533  75.80415144  43.33555066]
 [172.92575467  71.83398191  39.82236555]
 [177.          70.          40.        ]
 [162.43520793  68.70804444  38.60045973]
 [171.56160461  70.93330593  38.56773085]]

Primeiras 5 labels da nova base de dados (Y_larger):
['female' 'male' 'female' 'female' 'female']


In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn import tree
from sklearn import neighbors
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
import numpy as np

X = X_larger
Y = Y_larger
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=42)

# Inicializar os modelos
dt_clf = tree.DecisionTreeClassifier()
nc_clf = neighbors.NearestCentroid()
lda_clf = LinearDiscriminantAnalysis()
qda_clf = QuadraticDiscriminantAnalysis()

# Treinar os modelos com os dados de treino da base maior
dt_clf.fit(X_train, y_train)
nc_clf.fit(X_train, y_train)
lda_clf.fit(X_train, y_train)
qda_clf.fit(X_train, y_train)

# Fazer previsões nos dados de teste
dt_pred = dt_clf.predict(X_test)
nc_pred = nc_clf.predict(X_test)
lda_pred = lda_clf.predict(X_test)
qda_pred = qda_clf.predict(X_test)

# Calcular a acurácia de cada modelo
dt_accuracy = accuracy_score(y_test, dt_pred)
nc_accuracy = accuracy_score(y_test, nc_pred)
lda_accuracy = accuracy_score(y_test, lda_pred)
qda_accuracy = accuracy_score(y_test, qda_pred)

print(f"Acurácia da Árvore de Decisão: {dt_accuracy:.2f}")
print(f"Acurácia do Nearest Centroid: {nc_accuracy:.2f}")
print(f"Acurácia do Linear Discriminant Analysis: {lda_accuracy:.2f}")
print(f"Acurácia do Quadratic Discriminant Analysis: {qda_accuracy:.2f}")

# Determinar o melhor modelo (com base na acurácia neste conjunto de teste)
accuracies = {
    "Decision Tree": dt_accuracy,
    "Nearest Centroid": nc_accuracy,
    "Linear Discriminant Analysis": lda_accuracy,
    "Quadratic Discriminant Analysis": qda_accuracy
}

best_model = max(accuracies, key=accuracies.get)
print(f"\nO melhor modelo (com base na acurácia no conjunto de teste) é: {best_model}")

Acurácia da Árvore de Decisão: 0.58
Acurácia do Nearest Centroid: 0.81
Acurácia do Linear Discriminant Analysis: 0.77
Acurácia do Quadratic Discriminant Analysis: 0.77

O melhor modelo (com base na acurácia no conjunto de teste) é: Nearest Centroid
